/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cephra.PhonePanels;

/**
 *
 * @author usher
 */
public class Phonelogin extends javax.swing.JPanel {

    /**
     * Creates new form Phonelogin
     */
    public Phonelogin() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(400, 750));
        setSize(400, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();



        try {
            java.net.URL imageUrl2 = getClass().getClassLoader().getResource("cephra/Photos/logi.png");
            if (imageUrl2 != null) {
                javax.swing.ImageIcon icon2 = new javax.swing.ImageIcon(imageUrl2);
                // Scale the image to fit the panel size
                java.awt.Image img2 = icon2.getImage();
                java.awt.Image scaledImg2 = img2.getScaledInstance(400, 750, java.awt.Image.SCALE_SMOOTH);
                jLabel2.setIcon(new javax.swing.ImageIcon(scaledImg2));
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            } else {
                System.err.println("Image not found: cephra/Photos/logi.png");
            }
        } catch (Exception e) {
            System.err.println("Error loading image: " + e.getMessage());
        }

        // Configure jButton2 for transition
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setText("");
        jButton2.setPreferredSize(new java.awt.Dimension(400, 750));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your transition logic here
        System.out.println("jButton2 clicked - transition to next panel");
        // You can add navigation logic here to go to the next panel
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
