/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cephra.PhonePanels;

/**
 *
 * @author usher
 */
public class Phonelogin extends javax.swing.JPanel {

    /**
     * Creates new form Phonelogin
     */
    public Phonelogin() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(350, 750));
        setSize(350, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        
        // Match Splashscreen/Register panel transparency
        setOpaque(false);
        setBackground(new java.awt.Color(0, 0, 0, 0));

        // Make the register button invisible but clickable (like Splashscreen)
        regbutton.setOpaque(false);
        regbutton.setContentAreaFilled(false);
        regbutton.setBorderPainted(false);
        regbutton.setFocusPainted(false);
        regbutton.setText("");
        regbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbuttonActionPerformed(evt);
            }
        });
        add(regbutton);
        // Position to cover intended tap area; adjust if needed
        regbutton.setBounds(-14, -32, 400, 814);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cephra/Photos/LOGIN.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 814));
        jLabel1.setOpaque(false);
        add(jLabel1);
        jLabel1.setBounds(-14, -32, 400, 814);
    }// </editor-fold>//GEN-END:initComponents

    private void regbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbuttonActionPerformed
        // Navigate to Register panel (same approach as Splashscreen)
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                java.awt.Window[] windows = java.awt.Window.getWindows();
                for (java.awt.Window window : windows) {
                    if (window instanceof cephra.PhoneFrame) {
                        cephra.PhoneFrame phoneFrame = (cephra.PhoneFrame) window;
                        phoneFrame.switchPanel(new cephra.PhonePanels.Register());
                        break;
                    }
                }
            }
        });
    }//GEN-LAST:event_regbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your transition logic here
        System.out.println("jButton2 clicked - transition to next panel");
        // You can add navigation logic here to go to the next panel
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regbutton;
    // End of variables declaration//GEN-END:variables
}
