package cephra.PhonePanels;

public class Splashscreen extends javax.swing.JPanel {
   
    public Splashscreen() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(350, 750));
        setSize(350, 750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        t = new javax.swing.JLabel();

        setLayout(null);
        
        // Set panel background to transparent and add curved edges
        setOpaque(false);
        setBackground(new java.awt.Color(0, 0, 0, 0));

        // Configure jButton2 for transition
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setText(""); // Remove text
        jButton2.setVisible(false); // Make completely invisible
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(-14, -32, 400, 814); // Cover entire panel including overflow

        t.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cephra/Photos/GET STARTED.png"))); // NOI18N
        t.setPreferredSize(new java.awt.Dimension(400, 814));
        t.setOpaque(false);
        add(t);
        t.setBounds(-14, -32, 400, 814);
    }// </editor-fold>//GEN-END:initComponents





    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate to Phonelogin panel
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                // Find the PhoneFrame and switch to Phonelogin
                java.awt.Window[] windows = java.awt.Window.getWindows();
                for (java.awt.Window window : windows) {
                    if (window instanceof cephra.PhoneFrame) {
                        cephra.PhoneFrame phoneFrame = (cephra.PhoneFrame) window;
                        phoneFrame.switchPanel(new cephra.PhonePanels.Phonelogin());
                        break;
                    }
                }
            }
        });
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate to Phonelogin panel
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                // Find the PhoneFrame and switch to Phonelogin
                java.awt.Window[] windows = java.awt.Window.getWindows();
                for (java.awt.Window window : windows) {
                    if (window instanceof cephra.PhoneFrame) {
                        cephra.PhoneFrame phoneFrame = (cephra.PhoneFrame) window;
                        phoneFrame.switchPanel(new cephra.PhonePanels.Phonelogin());
                        break;
                    }
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
