/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cephra.Phone.Popups;

/**
 *
 * @author Kenji
 */
public class InsufficientBalPOP extends javax.swing.JPanel {

    /**
     * Creates new form InsufficientBalPOP
     */
    public InsufficientBalPOP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopUpBTN = new javax.swing.JButton();
        InsufficientCurrBal = new javax.swing.JLabel();
        InsufficientRequiredAmount = new javax.swing.JLabel();
        InsufficientShortage = new javax.swing.JLabel();
        EXT = new javax.swing.JButton();
        ICON = new javax.swing.JLabel();

        setLayout(null);

        TopUpBTN.setBorder(null);
        TopUpBTN.setBorderPainted(false);
        TopUpBTN.setContentAreaFilled(false);
        add(TopUpBTN);
        TopUpBTN.setBounds(60, 293, 210, 35);

        InsufficientCurrBal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsufficientCurrBal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InsufficientCurrBal.setText("jLabel1");
        add(InsufficientCurrBal);
        InsufficientCurrBal.setBounds(180, 169, 100, 16);

        InsufficientRequiredAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsufficientRequiredAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InsufficientRequiredAmount.setText("jLabel2");
        add(InsufficientRequiredAmount);
        InsufficientRequiredAmount.setBounds(180, 193, 100, 16);

        InsufficientShortage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsufficientShortage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        InsufficientShortage.setText("jLabel3");
        add(InsufficientShortage);
        InsufficientShortage.setBounds(180, 217, 100, 16);

        EXT.setBorder(null);
        EXT.setBorderPainted(false);
        EXT.setContentAreaFilled(false);
        add(EXT);
        EXT.setBounds(260, 30, 30, 30);

        ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cephra/Cephra Images/InsufficientBalPOP.png"))); // NOI18N
        add(ICON);
        ICON.setBounds(30, 20, 270, 330);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXT;
    private javax.swing.JLabel ICON;
    private javax.swing.JLabel InsufficientCurrBal;
    private javax.swing.JLabel InsufficientRequiredAmount;
    private javax.swing.JLabel InsufficientShortage;
    private javax.swing.JButton TopUpBTN;
    // End of variables declaration//GEN-END:variables
}
