/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cephra.Phone.Popups;

/**
 *
 * @author Kenji
 */
public class TransacHistoryDetailsPOP extends javax.swing.JPanel {

    /**
     * Creates new form TransacHistoryDetails
     */
    public TransacHistoryDetailsPOP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TransacTicketID = new javax.swing.JLabel();
        TransacUser = new javax.swing.JLabel();
        TransacDate = new javax.swing.JLabel();
        TransacTime = new javax.swing.JLabel();
        TransacAmount = new javax.swing.JLabel();
        OKBTN = new javax.swing.JButton();
        EXT = new javax.swing.JButton();
        ICON = new javax.swing.JLabel();

        setLayout(null);

        TransacTicketID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransacTicketID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TransacTicketID.setText("jLabel2");
        add(TransacTicketID);
        TransacTicketID.setBounds(160, 100, 100, 16);

        TransacUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransacUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TransacUser.setText("jLabel3");
        add(TransacUser);
        TransacUser.setBounds(160, 130, 100, 16);

        TransacDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransacDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TransacDate.setText("jLabel4");
        add(TransacDate);
        TransacDate.setBounds(160, 160, 100, 16);

        TransacTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TransacTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TransacTime.setText("jLabel5");
        add(TransacTime);
        TransacTime.setBounds(160, 190, 100, 16);

        TransacAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TransacAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TransacAmount.setText("jLabel6");
        add(TransacAmount);
        TransacAmount.setBounds(160, 235, 100, 20);

        OKBTN.setBorder(null);
        OKBTN.setBorderPainted(false);
        OKBTN.setContentAreaFilled(false);
        OKBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(OKBTN);
        OKBTN.setBounds(36, 287, 215, 34);

        EXT.setBorder(null);
        EXT.setBorderPainted(false);
        EXT.setContentAreaFilled(false);
        add(EXT);
        EXT.setBounds(235, 30, 40, 20);

        ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cephra/Cephra Images/TransacHistoryDetailsPOP.png"))); // NOI18N
        add(ICON);
        ICON.setBounds(10, 0, 270, 360);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXT;
    private javax.swing.JLabel ICON;
    private javax.swing.JButton OKBTN;
    private javax.swing.JLabel TransacAmount;
    private javax.swing.JLabel TransacDate;
    private javax.swing.JLabel TransacTicketID;
    private javax.swing.JLabel TransacTime;
    private javax.swing.JLabel TransacUser;
    // End of variables declaration//GEN-END:variables
}
